#!/bin/bash

# edit the starter code so that it looks like the finished code.
# Find 4 unique vim key combinations (where you use more than one key in normal mode) to make these edits.

alias ls="ls -aF --color=auto --group-directories-first"
alias cd="cd $(find -type d | fzf)"

if ! shopt -oq posix; then
	if [-f /usr/share/bash-completion/bash_completion ]; then
		./usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion]; then
		. /etc/bash_completion
	fi
fi


#finished code, don't copy and paste from this
# #!/bin/bash
# alias ls="ls -aF --color=auto --group-directories-first"
# alias cd="cd $(find -type d | fzf)"
# 
# if ! shopt -oq posix; then
#   if [ -f /usr/share/bash-completion/bash_completion ]; then
#     . /usr/share/bash-completion/bash_completion
#   elif [ -f /etc/bash_completion ]; then
#     . /etc/bash_completion
#   fi
# fi
# 
# 
# mkd() {
#   mkdir "$1" -p && cd "$1"
# }
